#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action="start" --log_path="systemd" --wait_until="Ui.UiServer Web interface" --timeout=120

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression "Integrating service in YunoHost..."

ynh_replace --match="$old_domain" --replace="$new_domain" --file="/etc/systemd/system/${app}.service"
systemctl daemon-reload

#=================================================
# START SYSTEMD SERVICE
#=================================================

ynh_systemctl --service="$app" --action="start" --log_path="systemd" --wait_until="Ui.UiServer Web interface" --timeout=120

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
