#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

path="/"

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

# Password are not saved by default, but here required for upgrade
ynh_app_setting_set --key=password --value="$password"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir/source"

#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod 750 "$install_dir"
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod -R o-rwx "$install_dir"
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R "$app:$app" "$install_dir"
chmod 750 "$data_dir"
chmod -R o-rwx "$data_dir"
chown -R "$app:$app" "$data_dir"

#=================================================
# SPECIFIC SETUP
#=================================================
# BUILDING ZERONET
#=================================================
ynh_script_progression "Building zeronet..."

ynh_exec_as_app python3 -m venv --upgrade "$install_dir/venv"
ynh_exec_as_app "$install_dir/venv/bin/python3" -m pip install --upgrade pip
ynh_exec_as_app "$install_dir/venv/bin/python3" -m pip install -r "$install_dir/source/requirements.txt"

# Enable password authentication for Zeronet
mv "$install_dir/source/plugins/disabled-UiPassword"  "$install_dir/source/plugins/UiPassword"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd
yunohost service add "$app" --description="$app service" --log="$data_dir/log/debug-last.log" --needs_exposed_ports="$port_fs"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app" --action="start" --log_path="systemd" --wait_until="Ui.UiServer Web interface" --timeout=120

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
